<h1>Settyl</h1>

In [192]:
import pandas as pd

url = 'https://gist.githubusercontent.com/farhaan-settyl/ecf9c1e7ab7374f18e4400b7a3d2a161/raw/f94652f217eeca83e36dab9d08727caf79ebdecf/dataset.json'
df = pd.read_json(url)
print(df.head(5))

                                      externalStatus    internalStatus
0                                           PORT OUT          Port Out
1                                        TERMINAL IN  Inbound Terminal
2                                            PORT IN           Port In
3  Vessel departure from first POL (Vessel name :...         Departure
4  Vessel arrival at final POD (Vessel name : TIA...           Arrival


In [193]:
df.describe()

externalStatus    internalStatus
count            1222              1222
unique            108                15
top          Gate out  Loaded on Vessel
freq              144               331

In [194]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222 entries, 0 to 1221
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   externalStatus  1222 non-null   object
 1   internalStatus  1222 non-null   object
dtypes: object(2)
memory usage: 19.2+ KB


In [195]:
df


externalStatus  \
0                                              PORT OUT   
1                                           TERMINAL IN   
2                                               PORT IN   
3     Vessel departure from first POL (Vessel name :...   
4     Vessel arrival at final POD (Vessel name : TIA...   
...                                                 ...   
1217                              Import Loaded on Rail   
1218                          Full Transshipment Loaded   
1219                          Full Transshipment Loaded   
1220                            Export Loaded on Vessel   
1221                                   Empty to Shipper   

                internalStatus  
0                     Port Out  
1             Inbound Terminal  
2                      Port In  
3                    Departure  
4                      Arrival  
...                        ...  
1217          Loaded on Vessel  
1218          Loaded on Vessel  
1219          Loaded on Vessel  
1220          Loaded on Vessel  
1221  Empty Container Released  

[1222 rows x 2 columns]

In [196]:
df.externalStatus

0                                                PORT OUT
1                                             TERMINAL IN
2                                                 PORT IN
3       Vessel departure from first POL (Vessel name :...
4       Vessel arrival at final POD (Vessel name : TIA...
                              ...                        
1217                                Import Loaded on Rail
1218                            Full Transshipment Loaded
1219                            Full Transshipment Loaded
1220                              Export Loaded on Vessel
1221                                     Empty to Shipper
Name: externalStatus, Length: 1222, dtype: object

In [197]:
import re
import pandas as pd
def clean(text):
  lowercase_text = text.lower()
  cleaned_string = re.sub(r'\[.*?\]|\(.*?\)|\'.*?\'|[0-9]{3}[a-z]', '', lowercase_text)
  return cleaned_string

result = map(clean, df.externalStatus)
result_list = list(result)

new_df = pd.DataFrame({'externalStatus': result_list , 'internalStatus': df.internalStatus})


In [198]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1222 entries, 0 to 1221
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   externalStatus  1222 non-null   object
 1   internalStatus  1222 non-null   object
dtypes: object(2)
memory usage: 19.2+ KB


In [199]:
new_df

externalStatus            internalStatus
0                             port out                  Port Out
1                          terminal in          Inbound Terminal
2                              port in                   Port In
3     vessel departure from first pol                  Departure
4         vessel arrival at final pod                    Arrival
...                                ...                       ...
1217             import loaded on rail          Loaded on Vessel
1218         full transshipment loaded          Loaded on Vessel
1219         full transshipment loaded          Loaded on Vessel
1220           export loaded on vessel          Loaded on Vessel
1221                  empty to shipper  Empty Container Released

[1222 rows x 2 columns]

In [200]:
from sklearn.model_selection import train_test_split
X=new_df.externalStatus
y=new_df.internalStatus
X_train, X_test, y_train, y_test = train_test_split(result_list, df.internalStatus, test_size=0.3, random_state=42)


In [201]:

import tensorflow as tf
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
out_X_train = vectorizer.fit_transform(X_train)
features_encoded=out_X_train.toarray()  # Convert the sparse matrix to a dense matrix for printing
features=vectorizer.get_feature_names_out()  # Get the names of the features (tokens)


In [202]:
features_encoded


array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [203]:
y_train

578            Departure
1196    Loaded on Vessel
215             Gate Out
1133    Loaded on Vessel
27              Off Rail
              ...       
1044             On Rail
1095            Gate Out
1130    Loaded on Vessel
860            Departure
1126    Loaded on Vessel
Name: internalStatus, Length: 855, dtype: object

In [204]:
# prompt: one hot encode y_train (use 0,1 instead false,true)


import pandas as pd
y_train_encoded = pd.get_dummies(y_train)


In [205]:
y_train_encoded

Arrival  Departure  Empty Container Released  Empty Return  Gate In  \
578     False       True                     False         False    False   
1196    False      False                     False         False    False   
215     False      False                     False         False    False   
1133    False      False                     False         False    False   
27      False      False                     False         False    False   
...       ...        ...                       ...           ...      ...   
1044    False      False                     False         False    False   
1095    False      False                     False         False    False   
1130    False      False                     False         False    False   
860     False       True                     False         False    False   
1126    False      False                     False         False    False   

      Gate Out  In-transit  Inbound Terminal  Loaded on Vessel  Off Rail  \
578      False       False             False             False     False   
1196     False       False             False              True     False   
215       True       False             False             False     False   
1133     False       False             False              True     False   
27       False       False             False             False      True   
...        ...         ...               ...               ...       ...   
1044     False       False             False             False     False   
1095      True       False             False             False     False   
1130     False       False             False              True     False   
860      False       False             False             False     False   
1126     False       False             False              True     False   

      On Rail  Outbound Terminal  Port In  Port Out  Unloaded on Vessel  
578     False              False    False     False               False  
1196    False              False    False     False               False  
215     False              False    False     False               False  
1133    False              False    False     False               False  
27      False              False    False     False               False  
...       ...                ...      ...       ...                 ...  
1044     True              False    False     False               False  
1095    False              False    False     False               False  
1130    False              False    False     False               False  
860     False              False    False     False               False  
1126    False              False    False     False               False  

[855 rows x 15 columns]

In [206]:
column_names_y_train = y_train_encoded.columns
print(column_names_y_train)

Index(['Arrival', 'Departure', 'Empty Container Released', 'Empty Return',
       'Gate In', 'Gate Out', 'In-transit', 'Inbound Terminal',
       'Loaded on Vessel', 'Off Rail', 'On Rail', 'Outbound Terminal',
       'Port In', 'Port Out', 'Unloaded on Vessel'],
      dtype='object')


In [207]:
y_train_encoded=y_train_encoded.replace({True: 1, False: 0})

In [208]:
y_train_encoded

Arrival  Departure  Empty Container Released  Empty Return  Gate In  \
578         0          1                         0             0        0   
1196        0          0                         0             0        0   
215         0          0                         0             0        0   
1133        0          0                         0             0        0   
27          0          0                         0             0        0   
...       ...        ...                       ...           ...      ...   
1044        0          0                         0             0        0   
1095        0          0                         0             0        0   
1130        0          0                         0             0        0   
860         0          1                         0             0        0   
1126        0          0                         0             0        0   

      Gate Out  In-transit  Inbound Terminal  Loaded on Vessel  Off Rail  \
578          0           0                 0                 0         0   
1196         0           0                 0                 1         0   
215          1           0                 0                 0         0   
1133         0           0                 0                 1         0   
27           0           0                 0                 0         1   
...        ...         ...               ...               ...       ...   
1044         0           0                 0                 0         0   
1095         1           0                 0                 0         0   
1130         0           0                 0                 1         0   
860          0           0                 0                 0         0   
1126         0           0                 0                 1         0   

      On Rail  Outbound Terminal  Port In  Port Out  Unloaded on Vessel  
578         0                  0        0         0                   0  
1196        0                  0        0         0                   0  
215         0                  0        0         0                   0  
1133        0                  0        0         0                   0  
27          0                  0        0         0                   0  
...       ...                ...      ...       ...                 ...  
1044        1                  0        0         0                   0  
1095        0                  0        0         0                   0  
1130        0                  0        0         0                   0  
860         0                  0        0         0                   0  
1126        0                  0        0         0                   0  

[855 rows x 15 columns]

In [209]:
import pickle
with open('features.pkl', 'wb') as f:
    pickle.dump(features, f)

print("features saved successfully.")

features saved successfully.


In [210]:
len(features)

99

In [211]:
y_train_encoded.shape


(855, 15)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Flatten

model = Sequential()

model.add(Dense(15, activation='sigmoid', input_shape=(99,)))

# Compile the model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Print the model summary
model.summary()


In [212]:
print(f"features_encoded shape: {features_encoded.shape}")
print(f"y_train_encoded shape: {y_train_encoded.shape}")

features_encoded shape: (855, 99)
y_train_encoded shape: (855, 15)


In [213]:
print(features_encoded)
print(f"features_encoded shape: {features_encoded.shape}")


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
features_encoded shape: (855, 99)


In [214]:
if features_encoded.shape[0] != y_train_encoded.shape[0]:
  raise ValueError("The first dimension of features_encoded and y_train_encoded must be equal.")

In [215]:


model.fit(features_encoded,y_train_encoded , epochs=25)


Epoch 1/25
27/27 [==============================] - 0s 3ms/step - loss: 0.4037 - accuracy: 0.9474
Epoch 2/25
27/27 [==============================] - 0s 3ms/step - loss: 0.3937 - accuracy: 0.9474
Epoch 3/25
27/27 [==============================] - 0s 5ms/step - loss: 0.3839 - accuracy: 0.9474
Epoch 4/25
27/27 [==============================] - 0s 4ms/step - loss: 0.3747 - accuracy: 0.9474
Epoch 5/25
27/27 [==============================] - 0s 5ms/step - loss: 0.3656 - accuracy: 0.9474
Epoch 6/25
27/27 [==============================] - 0s 5ms/step - loss: 0.3569 - accuracy: 0.9474
Epoch 7/25
27/27 [==============================] - 0s 4ms/step - loss: 0.3484 - accuracy: 0.9474
Epoch 8/25
27/27 [==============================] - 0s 4ms/step - loss: 0.3404 - accuracy: 0.9474
Epoch 9/25
27/27 [==============================] - 0s 4ms/step - loss: 0.3325 - accuracy: 0.9485
Epoch 10/25
27/27 [==============================] - 0s 5ms/step - loss: 0.3248 - accuracy: 0.9485
Epoch 11/25
27/27 [

In [216]:
import pickle


with open('model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model saved successfully.")

Model saved successfully.


In [217]:
def match_label(given_str,features_depends):
  a = [0] * len(features_depends)  # Initialize with zeros
  for i in range(len(features_depends)):
    if features_depends[i] in given_str:
      a[i]=1
  return a

In [218]:
X_test_array = []
for x in X_test:
    X_test_array.append(match_label(x,features))

In [219]:
import numpy as np
X_test_array = np.array(X_test_array)
print(X_test_array.shape)

(367, 99)


In [220]:

predictions = model.predict(X_test_array)


12/12 [==============================] - 0s 2ms/step


In [221]:
predictions

array([[0.03024121, 0.02177716, 0.05984105, ..., 0.01142814, 0.04230901,
        0.03282003],
       [0.12770681, 0.8958027 , 0.10808292, ..., 0.09145646, 0.10078224,
        0.1359401 ],
       [0.20173723, 0.32236284, 0.05624722, ..., 0.3206831 , 0.47461545,
        0.17669356],
       ...,
       [0.14187762, 0.06843407, 0.03088064, ..., 0.09454894, 0.03037643,
        0.04401146],
       [0.0531333 , 0.07258154, 0.05178525, ..., 0.03534373, 0.04206932,
        0.0308587 ],
       [0.03735158, 0.06100271, 0.03630056, ..., 0.02656829, 0.05935651,
        0.02391219]], dtype=float32)

In [222]:
num_rows, num_cols = predictions.shape
y_pred = [None] * num_rows
for i in range(num_rows):  # Iterate over each row
  max_index = 0
  for k in range(1, num_cols):  # Find the index of the maximum value
    if predictions[i][k] > predictions[i][max_index]:
      max_index = k
  for k in range(num_cols):
    if k == max_index:
      y_pred[i]=column_names_y_train[max_index]



In [223]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)


Accuracy: 0.9427792915531336


<h1>FAST API -</h1>


In [189]:
!pip install fastapi

In [224]:
!pip install uvicorn

In [225]:
from pydantic import BaseModel
class ResponseQuery(BaseModel):
    externalStatus: str

from fastapi import FastAPI, Request, HTTPException
from fastapi.responses import JSONResponse
import pickle
import numpy as np

with open('model.pkl', 'rb') as f:
    model = pickle.load(f)

with open('features.pkl', 'rb') as f:
    features = pickle.load(f)

app = FastAPI()

@app.post("/predict")
async def predict(data:ResponseQuery):
    data = data.dict()
    text = data["externalStatus"]
    if text is None:
        raise HTTPException(status_code=400, detail="Missing text input")

    def clean(text):
        lowercase_text = text.lower()
        cleaned_string = re.sub(r'\[.*?\]|\(.*?\)|\'.*?\'|[0-9]{3}[a-z]', '', lowercase_text)
        return cleaned_string

    cleaned_text = clean(text)

    def match_label(given_str, features_depends):
        a = [0] * len(features_depends)  # Initialize with zeros
        for i in range(len(features_depends)):
            if features_depends[i] in given_str:
                a[i]=1
        return a

    X_test_array = match_label(cleaned_text, features)
    X_test_array = np.array([X_test_array])

    prediction = model.predict(X_test_array)

    num_rows, num_cols = prediction.shape
    y_pred = [None] * num_rows
    for i in range(num_rows):
        max_index = 0
        for k in range(1, num_cols):
            if prediction[i][k] > prediction[i][max_index]:
                max_index = k
        for k in range(num_cols):
            if k == max_index:
                y_pred[i]=column_names_y_train[max_index]

    return JSONResponse({"prediction": y_pred[0]})

In [226]:
!pip install colabcode

In [227]:
from colabcode import ColabCode
!ngrok config add-authtoken 2erxMJBy1CkjlslheA5woJTIceB_4imVLWCkSFkv7qwqaWS7Y
cc = ColabCode(port=12000,code=False)
cc.run_app(app=app)

Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Public URL: NgrokTunnel: "https://6e17-35-204-143-71.ngrok-free.app" -> "http://localhost:12000"


INFO:     Started server process [294]
INFO:uvicorn.error:Started server process [294]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://127.0.0.1:12000 (Press CTRL+C to quit)


INFO:     2409:40c0:6a:7e22:e031:4574:547d:cba3:0 - "GET / HTTP/1.1" 404 Not Found
INFO:     2409:40c0:6a:7e22:e031:4574:547d:cba3:0 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     2409:40c0:6a:7e22:e031:4574:547d:cba3:0 - "GET /docs HTTP/1.1" 200 OK
INFO:     2409:40c0:6a:7e22:e031:4574:547d:cba3:0 - "GET /openapi.json HTTP/1.1" 200 OK
1/1 [==============================] - 0s 41ms/step
INFO:     2409:40c0:6a:7e22:e031:4574:547d:cba3:0 - "POST /predict HTTP/1.1" 200 OK


INFO:     Shutting down
INFO:uvicorn.error:Shutting down
INFO:     Waiting for application shutdown.
INFO:uvicorn.error:Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:uvicorn.error:Application shutdown complete.
INFO:     Finished server process [294]
INFO:uvicorn.error:Finished server process [294]
